wget https://portal.nersc.gov/cfs/cosmo/data/legacysurvey/dr10/randoms/randoms-allsky-1-0.fits
wget https://portal.nersc.gov/cfs/cosmo/data/legacysurvey/dr10/randoms/randoms-allsky-1-1.fits
wget https://portal.nersc.gov/cfs/cosmo/data/legacysurvey/dr10/randoms/randoms-allsky-1-2.fits
wget https://portal.nersc.gov/cfs/cosmo/data/legacysurvey/dr10/randoms/randoms-allsky-1-3.fits
wget https://portal.nersc.gov/cfs/cosmo/data/legacysurvey/dr10/randoms/randoms-allsky-1-4.fits
wget https://portal.nersc.gov/cfs/cosmo/data/legacysurvey/dr10/randoms/randoms-allsky-1-5.fits
wget https://portal.nersc.gov/cfs/cosmo/data/legacysurvey/dr10/randoms/randoms-allsky-1-6.fits
wget https://portal.nersc.gov/cfs/cosmo/data/legacysurvey/dr10/randoms/randoms-allsky-1-7.fits
wget https://portal.nersc.gov/cfs/cosmo/data/legacysurvey/dr10/randoms/randoms-allsky-1-8.fits
wget https://portal.nersc.gov/cfs/cosmo/data/legacysurvey/dr10/randoms/randoms-allsky-1-9.fits
wget https://portal.nersc.gov/cfs/cosmo/data/legacysurvey/dr10/randoms/randoms-allsky-1-10.fits
wget https://portal.nersc.gov/cfs/cosmo/data/legacysurvey/dr10/randoms/randoms-allsky-1-11.fits
wget https://portal.nersc.gov/cfs/cosmo/data/legacysurvey/dr10/randoms/randoms-allsky-1-12.fits
wget https://portal.nersc.gov/cfs/cosmo/data/legacysurvey/dr10/randoms/randoms-allsky-1-13.fits
wget https://portal.nersc.gov/cfs/cosmo/data/legacysurvey/dr10/randoms/randoms-allsky-1-14.fits
wget https://portal.nersc.gov/cfs/cosmo/data/legacysurvey/dr10/randoms/randoms-allsky-1-15.fits
wget https://portal.nersc.gov/cfs/cosmo/data/legacysurvey/dr10/randoms/randoms-allsky-1-16.fits
wget https://portal.nersc.gov/cfs/cosmo/data/legacysurvey/dr10/randoms/randoms-allsky-1-17.fits
wget https://portal.nersc.gov/cfs/cosmo/data/legacysurvey/dr10/randoms/randoms-allsky-1-18.fits
wget https://portal.nersc.gov/cfs/cosmo/data/legacysurvey/dr10/randoms/randoms-allsky-1-19.fits